const ADDMAX='ADDMIX'
const CHANGESELECT='CHANGESELECT'
const SELECTALLQAS='SELECTALLQAS'
const CHANGESELECTQAS='CHANGESELECTQAS'
const CHANGEQAS='CHANGEQAS'
const MODIFYSAVE='MODIFYSAVE'

export {
    ADDMAX,CHANGESELECT,SELECTALLQAS,CHANGESELECTQAS,CHANGEQAS,MODIFYSAVE
}